/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'romansova' at '6/23/15 1:56 PM' with Gradle 2.1
 *
 * @author romansova, @date 6/23/15 1:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
