/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'romansova' at '11/1/14 12:24 PM' with Gradle 2.1
 *
 * @author romansova, @date 11/1/14 12:24 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
