/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'romansova' at '4/28/15 9:48 AM' with Gradle 2.1
 *
 * @author romansova, @date 4/28/15 9:48 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
