/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'romansova' at '4/28/15 9:48 AM' with Gradle 2.1
 *
 * @author romansova, @date 4/28/15 9:48 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
